service: aws-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:331317819209:table/AdsTab

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
  createAd: 
    handler: src/ads/createAd.createAd
    events:
      - httpApi:
          path: /ads
          method: post
  getAds: 
    handler: src/ads/getAds.getAds
    events:
      - httpApi:
          path: /ads
          method: get
  getAd: 
    handler: src/ads/getAd.getAd
    events:
      - httpApi:
          path: /ads/{id}
          method: get
  updateAd: 
    handler: src/ads/updateAd.updateAd
    events:
      - httpApi:
          path: /ads/{id}
          method: put
  deleteAd: 
    handler: src/ads/deleteAd.deleteAd
    events:
      - httpApi:
          path: /ads/{id}
          method: delete
resources:
  Resources:
    AdsTab:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AdsTab
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH