service: aws-api-node
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:331317819209:table/AdsTable

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
  createAd: 
    handler: src/createAd.createAd
    events:
      - httpApi:
          path: /ads
          method: post
resources:
  Resources:
    AdsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AdsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH